### ISSUE TITLE
it's not work 

### ISSUE THREAD

**Issue by rosebless** [pubnub/chat-engine-examples#18]
in chat-engine-examples ( react ), i clone the project and open command (as adminnistrator) and follow the command :

1. pushd ...\chat-engine-examples-master\react
2. npm install 
3. npm start 

then output (http://localhost:3000/) is white page and get error : 

Failed to load resource: the server responded with a status of 500 (Internal Server Error)
bootstrap.js:82 Objecterror: Error: Request failed with status code 500
    at createError (http://localhost:3000/static/js/bundle.js:33126:16)
    at settle (http://localhost:3000/static/js/bundle.js:33093:13)
    at XMLHttpRequest.handleLoad (http://localhost:3000/static/js/bundle.js:32963:8)__proto__: Object
ChatEngine.throwError @ bootstrap.js:82
bootstrap.js:414 Uncaught (in promise) Error: There was a problem logging into the auth server (https://pubsub.pubnub.com/v1/blocks/sub-key/sub-c-6c6c021c-c4e2-11e7-9628-f616d8b03518/chat-engine-server).
    at async.parallel (bootstrap.js:414)
    at async.js:3888
    at async.js:473
    at iteratorCallback (async.js:1062)
    at async.js:969
    at async.js:3885
    at <anonymous>
pubsub.pubnub.com/v1/blocks/sub-key/sub-c-6c6c021c-c4e2-11e7-9628-f616d8b03518/chat-engine-server?route=user_read Failed to load resource: the server responded with a status of 500 (Internal Server Error)
pubsub.pubnub.com/v1/blocks/sub-key/sub-c-6c6c021c-c4e2-11e7-9628-f616d8b03518/chat-engine-server?route=group Failed to load resource: the server responded with a status of 500 (Internal Server Error)
pubsub.pubnub.com/v1/blocks/sub-key/sub-c-6c6c021c-c4e2-11e7-9628-f616d8b03518/chat-engine-server?route=user_write Failed to load resource: the server responded with a status of 500 (Internal Server Error)

-------------------------------------------------------------------------------------------------------------
i try change the Publish Key and Subscribe Key to
Publish Key : pub-c-428fb22b-3da8-41f8-b627-738f0e414668
Subscribe Key : sub-c-a2c937fe-ae88-11e8-b277-3a1ccc7672cd 
this my app key
in Application add-ons setting, i enable only ACCESS MANAGER 
i don't know how to set my app for use on chat 

after all  output (http://localhost:3000/) is white page and  i get another error : 
xhr.js:178 POST https://pubsub.pubnub.com/v1/blocks/sub-key/sub-c-a2c937fe-ae88-11e8-b277-3a1ccc7672cd/chat-engine-server?route=bootstrap 404 (Not Found)
dispatchXhrRequest @ xhr.js:178
xhrAdapter @ xhr.js:12
dispatchRequest @ dispatchRequest.js:52
Promise.then (async)
request @ Axios.js:58
Axios.(anonymous function) @ Axios.js:78
wrap @ bind.js:9
ChatEngine.request @ bootstrap.js:131
async.parallel @ bootstrap.js:395
(anonymous) @ async.js:3880
eachOfArrayLike @ async.js:1069
eachOf @ async.js:1117
_parallel @ async.js:3879
parallelLimit @ async.js:3962
ChatEngine.connect @ bootstrap.js:393
(anonymous) @ index.js:16
__webpack_require__ @ bootstrap 8be4022525d47c607d25:555
fn @ bootstrap 8be4022525d47c607d25:86
(anonymous) @ bootstrap 8be4022525d47c607d25:578
__webpack_require__ @ bootstrap 8be4022525d47c607d25:555
(anonymous) @ bootstrap 8be4022525d47c607d25:578
(anonymous) @ bootstrap 8be4022525d47c607d25:578
bootstrap.js:82 {error: Error: Request failed with status code 404
    at createError (http://localhost:3000/static/js/bundl…}
ChatEngine.throwError @ bootstrap.js:82
async.parallel @ bootstrap.js:414
(anonymous) @ async.js:3888
(anonymous) @ async.js:473
iteratorCallback @ async.js:1062
(anonymous) @ async.js:969
(anonymous) @ async.js:3885
Promise.catch (async)
async.parallel @ bootstrap.js:397
(anonymous) @ async.js:3880
eachOfArrayLike @ async.js:1069
eachOf @ async.js:1117
_parallel @ async.js:3879
parallelLimit @ async.js:3962
ChatEngine.connect @ bootstrap.js:393
(anonymous) @ index.js:16
__webpack_require__ @ bootstrap 8be4022525d47c607d25:555
fn @ bootstrap 8be4022525d47c607d25:86
(anonymous) @ bootstrap 8be4022525d47c607d25:578
__webpack_require__ @ bootstrap 8be4022525d47c607d25:555
(anonymous) @ bootstrap 8be4022525d47c607d25:578
(anonymous) @ bootstrap 8be4022525d47c607d25:578
xhr.js:178 POST https://pubsub.pubnub.com/v1/blocks/sub-key/sub-c-a2c937fe-ae88-11e8-b277-3a1ccc7672cd/chat-engine-server?route=group 404 (Not Found)
dispatchXhrRequest @ xhr.js:178
xhrAdapter @ xhr.js:12
dispatchRequest @ dispatchRequest.js:52
Promise.then (async)
request @ Axios.js:58
Axios.(anonymous function) @ Axios.js:78
wrap @ bind.js:9
ChatEngine.request @ bootstrap.js:131
async.parallel @ bootstrap.js:410
(anonymous) @ async.js:3880
eachOfArrayLike @ async.js:1069
eachOf @ async.js:1117
_parallel @ async.js:3879
parallelLimit @ async.js:3962
ChatEngine.connect @ bootstrap.js:393
(anonymous) @ index.js:16
__webpack_require__ @ bootstrap 8be4022525d47c607d25:555
fn @ bootstrap 8be4022525d47c607d25:86
(anonymous) @ bootstrap 8be4022525d47c607d25:578
__webpack_require__ @ bootstrap 8be4022525d47c607d25:555
(anonymous) @ bootstrap 8be4022525d47c607d25:578
(anonymous) @ bootstrap 8be4022525d47c607d25:578
xhr.js:178 POST https://pubsub.pubnub.com/v1/blocks/sub-key/sub-c-a2c937fe-ae88-11e8-b277-3a1ccc7672cd/chat-engine-server?route=user_write 404 (Not Found)
dispatchXhrRequest @ xhr.js:178
xhrAdapter @ xhr.js:12
dispatchRequest @ dispatchRequest.js:52
Promise.then (async)
request @ Axios.js:58
Axios.(anonymous function) @ Axios.js:78
wrap @ bind.js:9
ChatEngine.request @ bootstrap.js:131
async.parallel @ bootstrap.js:405
(anonymous) @ async.js:3880
eachOfArrayLike @ async.js:1069
eachOf @ async.js:1117
_parallel @ async.js:3879
parallelLimit @ async.js:3962
ChatEngine.connect @ bootstrap.js:393
(anonymous) @ index.js:16
__webpack_require__ @ bootstrap 8be4022525d47c607d25:555
fn @ bootstrap 8be4022525d47c607d25:86
(anonymous) @ bootstrap 8be4022525d47c607d25:578
__webpack_require__ @ bootstrap 8be4022525d47c607d25:555
(anonymous) @ bootstrap 8be4022525d47c607d25:578
(anonymous) @ bootstrap 8be4022525d47c607d25:578
xhr.js:178 POST https://pubsub.pubnub.com/v1/blocks/sub-key/sub-c-a2c937fe-ae88-11e8-b277-3a1ccc7672cd/chat-engine-server?route=user_read 404 (Not Found)
dispatchXhrRequest @ xhr.js:178
xhrAdapter @ xhr.js:12
dispatchRequest @ dispatchRequest.js:52
Promise.then (async)
request @ Axios.js:58
Axios.(anonymous function) @ Axios.js:78
wrap @ bind.js:9
ChatEngine.request @ bootstrap.js:131
async.parallel @ bootstrap.js:400
(anonymous) @ async.js:3880
eachOfArrayLike @ async.js:1069
eachOf @ async.js:1117
_parallel @ async.js:3879
parallelLimit @ async.js:3962
ChatEngine.connect @ bootstrap.js:393
(anonymous) @ index.js:16
__webpack_require__ @ bootstrap 8be4022525d47c607d25:555
fn @ bootstrap 8be4022525d47c607d25:86
(anonymous) @ bootstrap 8be4022525d47c607d25:578
__webpack_require__ @ bootstrap 8be4022525d47c607d25:555
(anonymous) @ bootstrap 8be4022525d47c607d25:578
(anonymous) @ bootstrap 8be4022525d47c607d25:578
bootstrap.js:414 Uncaught (in promise) Error: There was a problem logging into the auth server (https://pubsub.pubnub.com/v1/blocks/sub-key/sub-c-a2c937fe-ae88-11e8-b277-3a1ccc7672cd/chat-engine-server).
    at async.parallel (bootstrap.js:414)
    at async.js:3888
    at async.js:473
    at iteratorCallback (async.js:1062)
    at async.js:969
    at async.js:3885
    at <anonymous>
async.parallel @ bootstrap.js:414
(anonymous) @ async.js:3888
(anonymous) @ async.js:473
iteratorCallback @ async.js:1062
(anonymous) @ async.js:969
(anonymous) @ async.js:3885
Promise.catch (async)
async.parallel @ bootstrap.js:397
(anonymous) @ async.js:3880
eachOfArrayLike @ async.js:1069
eachOf @ async.js:1117
_parallel @ async.js:3879
parallelLimit @ async.js:3962
ChatEngine.connect @ bootstrap.js:393
(anonymous) @ index.js:16
__webpack_require__ @ bootstrap 8be4022525d47c607d25:555
fn @ bootstrap 8be4022525d47c607d25:86
(anonymous) @ bootstrap 8be4022525d47c607d25:578
__webpack_require__ @ bootstrap 8be4022525d47c607d25:555
(anonymous) @ bootstrap 8be4022525d47c607d25:578
(anonymous) @ bootstrap 8be4022525d47c607d25:578

**Comment by crgbaumgart** [comment]
@rosebless thank you for reporting your findings!  🎉 

From those connection errors it looks like you may be missing the server-side component. The pub/sub keys you provided should come from a PubNub account which has pre-configured the customer's pub/sub keys for ChatEngine usage.

You can find the setup info [here](https://www.pubnub.com/docs/chat-engine/getting-started). 

Couple clarifying questions for you: 
- Have you setup ChatEngine via [PubNub's ChatEngine Setup tool](https://www.pubnub.com/docs/chat-engine/getting-started)? Otherwise simply cloning the project will not work, as the client requires a backend (in this case a [PubNub Function](https://www.pubnub.com/products/functions/)).
- What version of node are you using? 6,7,& 8 have all been tested to work with ChatEngine v.0.9.18

Lemme know if you have any further issues!

**Comment by nishith-pubnub** [comment]
@rosebless I will set this ticket to RESOLVED. If the issue persists, definitely feel free to open a ticket with PubNub Support (https://support.pubnub.com).
